name: Lint

on:
  pull_request:
  push:
    branches: [main]

job:
  prettier:
    name: Prettier
    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4

      - name: Run prettier
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: prettier
